# Generated by Django 6.0.2 on 2026-03-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
