# Generated by Django 6.0.2 on 2026-03-25 11:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=20)),
                ('reg_no', models.CharField(blank=True, max_length=20, null=True)),
                ('student_name', models.CharField(max_length=100)),
                ('certificate_type', models.CharField(choices=[('resident', 'Resident Certificate'), ('nodues', 'No Dues Certificate'), ('estimation', 'Estimation Slip')], max_length=20)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessPayment',
            fields=[
                ('receipt_no', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=20)),
                ('room_no', models.CharField(max_length=10)),
                ('class_yr', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('month', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('payment_mode', models.CharField(max_length=20)),
                ('purpose', models.CharField(default='Mess Payment', max_length=50)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('aadhar', models.CharField(max_length=12)),
                ('admission_no', models.CharField(max_length=20, unique=True)),
                ('reg_no', models.CharField(blank=True, max_length=20, null=True)),
                ('class_yr', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=50)),
                ('roll_no', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('caste', models.CharField(max_length=50)),
                ('catering', models.CharField(max_length=20)),
                ('amount', models.CharField(default='13000', max_length=10)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('father_name', models.CharField(max_length=100)),
                ('father_phone', models.CharField(max_length=15)),
                ('father_aadhar', models.FileField(blank=True, null=True, upload_to='parents/father/aadhar/')),
                ('father_photo', models.ImageField(blank=True, null=True, upload_to='parents/father/photos/')),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_phone', models.CharField(max_length=15)),
                ('mother_aadhar', models.FileField(blank=True, null=True, upload_to='parents/mother/aadhar/')),
                ('mother_photo', models.ImageField(blank=True, null=True, upload_to='parents/mother/photos/')),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_phone', models.CharField(max_length=15)),
                ('guardian_aadhar', models.FileField(blank=True, null=True, upload_to='guardian/aadhar/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=20, unique=True)),
                ('reg_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('reset_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.studentregistration')),
            ],
        ),
    ]
