# Generated by Django 6.0.2 on 2026-04-11 07:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_certificate_messpayment_student_studentregistration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetotp',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='reset_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to='applications.studentregistration'),
        ),
    ]
