# Generated by Django 6.0.2 on 2026-04-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_passwordresetotp_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='block',
            field=models.CharField(blank=True, default='Not Allotted', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hostel_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='room_no',
            field=models.CharField(blank=True, default='Not Allotted', max_length=20, null=True),
        ),
    ]
