# Generated by Django 6.0.2 on 2026-04-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_student_block_student_hostel_name_student_room_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='messpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
