# Generated by Django 6.0.2 on 2026-04-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_messpayment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
    ]
