# Generated by Django 6.0.2 on 2026-04-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_alter_student_aadhar_alter_student_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.CharField(blank=True, choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('MSc', 'M.Sc')], max_length=10, null=True),
        ),
    ]
