# Generated by Django 6.0.2 on 2026-04-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_student_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_leaving',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='months_stayed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='room',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
