# Generated by Django 6.0.2 on 2026-04-21 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_student_is_leaving_student_months_stayed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField()),
                ('electric_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mess_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_demand', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collection', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('month', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='messpayment',
            name='days_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messpayment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mess_payments', to='applications.student'),
        ),
        migrations.AddField(
            model_name='messpayment',
            name='billing_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.billingrate'),
        ),
        migrations.CreateModel(
            name='StudentBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('billing_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.billingrate')),
                ('mess_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.messpayment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='applications.student')),
            ],
            options={
                'unique_together': {('student', 'month')},
            },
        ),
    ]
