# Generated by Django 6.0 on 2026-04-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_billingrate_messpayment_days_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWardenUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('warden', 'Warden')], max_length=10)),
            ],
        ),
    ]
