# Generated by Django 6.0 on 2026-04-23 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_billingrate_messpayment_days_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostelApplication',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
