# Generated by Django 6.0 on 2026-04-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_adminwardenuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(blank=True, choices=[('BTECH', 'B.Tech'), ('MTECH', 'M.Tech'), ('MSC', 'M.Sc'), ('DUAL', 'B.Tech + M.Tech')], max_length=10, null=True),
        ),
    ]
