# Generated by Django 6.0.2 on 2026-04-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_student_user'),
        ('applications', '0014_alter_student_degree'),
    ]

    operations = [
    ]
