# Generated by Django 6.0 on 2026-04-23 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_adminwardenuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to='applications.studentregistration'),
        ),
    ]
