# Generated by Django 6.0 on 2026-04-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_add_email_to_password_reset_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_1_floors', models.JSONField(blank=True, default=list)),
                ('year_2_floors', models.JSONField(blank=True, default=list)),
                ('year_3_floors', models.JSONField(blank=True, default=list)),
                ('year_4_floors', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to='applications.block')),
            ],
        ),
    ]