# Generated by Django 6.0.2 on 2026-04-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_remove_student_user_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messpayment',
            name='class_yr',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='messpayment',
            name='month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='messpayment',
            name='room_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_yr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='room_no',
            field=models.CharField(blank=True, default='Not Allotted', max_length=50, null=True),
        ),
    ]
