# Generated by Django 6.0.2 on 2026-04-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_alter_messpayment_class_yr_alter_messpayment_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messpayment',
            name='is_actual_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messpayment',
            name='payment_source',
            field=models.CharField(default='excel_import', max_length=20),
        ),
    ]
