# Generated by Django 6.0 on 2026-04-25 12:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminWardenUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('warden', 'Warden')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BillingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('days', models.IntegerField(default=0)),
                ('mess_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_demand', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=20)),
                ('reg_no', models.CharField(blank=True, max_length=20, null=True)),
                ('student_name', models.CharField(max_length=100)),
                ('certificate_type', models.CharField(choices=[('resident', 'Resident Certificate'), ('nodues', 'No Dues Certificate'), ('estimation', 'Estimation Slip')], max_length=20)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(max_length=50, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_mode', models.CharField(choices=[('online', 'Online'), ('cash', 'Cash')], default='online', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=20, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('aadhar', models.CharField(blank=True, max_length=12, null=True)),
                ('caste', models.CharField(blank=True, max_length=50, null=True)),
                ('admission_no', models.CharField(max_length=20, unique=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('degree', models.CharField(blank=True, choices=[('B.Tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('MSc', 'M.Sc')], max_length=10, null=True)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('class_yr', models.CharField(blank=True, max_length=10, null=True)),
                ('room_no', models.CharField(blank=True, default='Not Allotted', max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('amount', models.CharField(default='13000', max_length=10)),
                ('months_stayed', models.IntegerField(default=0)),
                ('is_leaving', models.BooleanField(default=False)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.CharField(blank=True, default='Not Allotted', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=20, unique=True)),
                ('reg_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('reset_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to='student.studentregistration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='student.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'month')},
            },
        ),
    ]
