# Generated by Django 6.0 on 2026-04-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_add_roll_no_to_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadhar_pdf',
            field=models.FileField(blank=True, null=True, upload_to='students/aadhar/'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_aadhar',
            field=models.FileField(blank=True, null=True, upload_to='parents/aadhar/'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_photo',
            field=models.FileField(blank=True, null=True, upload_to='parents/photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_aadhar',
            field=models.FileField(blank=True, null=True, upload_to='parents/aadhar/'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_photo',
            field=models.FileField(blank=True, null=True, upload_to='parents/photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_photo',
            field=models.FileField(blank=True, null=True, upload_to='students/photos/'),
        ),
    ]
