# Generated by Django 6.0 on 2026-04-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_add_photo_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='reg_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
