# Generated by Django 6.0 on 2026-04-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentregistration_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingrate',
            name='month',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
