# Generated by Django 6.0 on 2026-04-25 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_billingrate_month'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentbilling',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentbilling',
            name='roll_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentbilling',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='studentbilling',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='student.student'),
        ),
        migrations.AlterUniqueTogether(
            name='studentbilling',
            unique_together={('roll_no', 'month', 'year')},
        ),
    ]
