# Generated by Django 6.0 on 2026-04-26 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_studentbilling_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbilling',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentBillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(blank=True, max_length=20, null=True)),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(default='2024-25', max_length=10)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('july_data', models.JSONField(blank=True, default=dict)),
                ('august_data', models.JSONField(blank=True, default=dict)),
                ('september_data', models.JSONField(blank=True, default=dict)),
                ('october_data', models.JSONField(blank=True, default=dict)),
                ('november_data', models.JSONField(blank=True, default=dict)),
                ('december_data', models.JSONField(blank=True, default=dict)),
                ('january_data', models.JSONField(blank=True, default=dict)),
                ('february_data', models.JSONField(blank=True, default=dict)),
                ('march_data', models.JSONField(blank=True, default=dict)),
                ('april_data', models.JSONField(blank=True, default=dict)),
                ('may_data', models.JSONField(blank=True, default=dict)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='student.student')),
            ],
            options={
                'unique_together': {('roll_no', 'year')},
            },
        ),
    ]
